services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - '8091:8090'
    volumes:
      - ./backend/pb_data:/app/pb_data
      - ./backend/pb_public:/app/pb_public
    restart: unless-stopped
