// Minimal type definitions to replace @/payload-types
// These were previously generated by Payload CMS; now defined locally.

export interface Media {
  id: string | number
  url?: string | null
  filename?: string | null
  alt?: string | null
  width?: number | null
  height?: number | null
  mimeType?: string | null
  sizes?: Record<string, { url?: string | null; width?: number | null; height?: number | null }> | null
  updatedAt?: string | null
  createdAt?: string | null
}

export interface Page {
  id: string | number
  slug?: string | null
  title?: string | null
}

export interface Post {
  id: string | number
  slug?: string | null
  title?: string | null
  categories?: (Category | string)[] | null
  meta?: {
    title?: string | null
    description?: string | null
    image?: Media | string | null
  } | null
}

export interface Category {
  id: string | number
  title?: string | null
}
